name: CI LaPlacita

on: 
    push:
        branches:
            - master 
    pull_request:
        branches:
            - master

jobs:
    test: 
        runs-on: ubuntu-latest

        steps:
        - name: Descargar código
          uses: actions/checkout@v4
        
        - name: Configurar Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'

        - name: Instalar dependencias
          run: npm ci

        - name: Ejecutar pruebas
          run: npm test

    sonar:
        runs-on: ubuntu-latest
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        steps:
        - name: Descargar código (historial completo)
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Configurar Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'

        - name: Instalar dependencias
          run: npm ci

        - name: Ejecutar pruebas
          run: npm test

        - name: Análisis estático con SonarCloud
          if: ${{ env.SONAR_TOKEN != '' }}
          uses: sonarsource/sonarcloud-github-action@v5
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        